//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace newSite {
    
    
    public partial class _Default {
        
        /// <summary>
        /// ctrBannerCarousel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.BannerCarousel ctrBannerCarousel;
        
        /// <summary>
        /// ImagePod1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.ImagePod ImagePod1;
        
        /// <summary>
        /// ImagePod2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.ImagePod ImagePod2;
        
        /// <summary>
        /// ImagePod3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.ImagePod ImagePod3;
        
        /// <summary>
        /// ImagePod4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.ImagePod ImagePod4;
        
        /// <summary>
        /// ImagePod5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.ImagePod ImagePod5;
        
        /// <summary>
        /// ImagePod6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.ImagePod ImagePod6;
        
        /// <summary>
        /// ctrSingePod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.SinglePod ctrSingePod;
        
        /// <summary>
        /// ctrOneColumn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.OneColumn ctrOneColumn;
    }
}
