//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace newSite {
    
    
    public partial class _Default {
        
        /// <summary>
        /// ctrBannerCarousel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.BannerCarousel ctrBannerCarousel;
        
        /// <summary>
        /// ctrSingePod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.SinglePod ctrSingePod;
        
        /// <summary>
        /// ctrImagePod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.ImagePod ctrImagePod;
        
        /// <summary>
        /// ctrOneColumn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::newSite.UserControls.OneColumn ctrOneColumn;
    }
}
